/**
 * AUTO-GENERATED from reports/peptide_trust_registry_v2.csv — DO NOT EDIT BY HAND.
 * Regenerate:  npm run gen:participants
 *
 * Source of truth is the CSV; logic/types live in ./participants.ts.
 * Scores/tiers are computed by @peptidetrust/core-scoring at generation time.
 */
import type { Participant } from './participants'

export const PARTICIPANTS_DATA: Participant[] = [
  {
    id: "p-001",
    display_name: "Bachem Holding AG",
    role_code: "MANUFACTURER",
    status: "ACTIVE",
    jurisdiction: "Швейцария (CH)",
    domain: "bachem.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 78.2,
    tier: "Platinum",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 100,
    tests_count: 45,
    updated_days_ago: 1,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0001seedmock",
    factors: [
      { code: "QEF", label: "Качество энзимов", value: 95, v_i: 0.9, freshness_di: 1, di_class: "A", contribution: 85.5 },
      { code: "TRF", label: "Тепловая резистентность", value: 92, v_i: 0.9, freshness_di: 1, di_class: "A", contribution: 82.8 },
      { code: "CCF", label: "Контроль концентрации", value: 92, v_i: 0.9, freshness_di: 1, di_class: "A", contribution: 82.8 },
      { code: "PCF", label: "Протокол чистоты", value: 90, v_i: 0.9, freshness_di: 1, di_class: "A", contribution: 81 },
      { code: "RF", label: "Поглощающая фракция", value: 90, v_i: 0.9, freshness_di: 1, di_class: "B", contribution: 81 },
      { code: "SCIF", label: "Стабильность цепочек", value: 88, v_i: 0.9, freshness_di: 1, di_class: "B", contribution: 79.2 },
      { code: "FRF", label: "Поглощение фрагментов", value: 88, v_i: 0.9, freshness_di: 1, di_class: "C", contribution: 79.2 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 78.2, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0001seedmock", computed_at: "2026-06-25T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.bachem.com" },
  },

  {
    id: "p-002",
    display_name: "PolyPeptide Group AG",
    role_code: "MANUFACTURER",
    status: "ACTIVE",
    jurisdiction: "Швейцария (CH)",
    domain: "polypeptide.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 75.4,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 100,
    tests_count: 40,
    updated_days_ago: 7,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0002seedmock",
    factors: [
      { code: "QEF", label: "Качество энзимов", value: 92, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 82.8 },
      { code: "SCIF", label: "Стабильность цепочек", value: 90, v_i: 0.9, freshness_di: 7, di_class: "B", contribution: 81 },
      { code: "CCF", label: "Контроль концентрации", value: 90, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 81 },
      { code: "PCF", label: "Протокол чистоты", value: 88, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 79.2 },
      { code: "TRF", label: "Тепловая резистентность", value: 88, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 79.2 },
      { code: "RF", label: "Поглощающая фракция", value: 88, v_i: 0.9, freshness_di: 7, di_class: "B", contribution: 79.2 },
      { code: "FRF", label: "Поглощение фрагментов", value: 85, v_i: 0.9, freshness_di: 7, di_class: "C", contribution: 76.5 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 75.4, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0002seedmock", computed_at: "2026-06-19T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.polypeptide.com" },
  },

  {
    id: "p-003",
    display_name: "Eurogentec S.A.",
    role_code: "MANUFACTURER",
    status: "ACTIVE",
    jurisdiction: "Бельгия (BE)",
    domain: "eurogentec.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 71.1,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 100,
    tests_count: 30,
    updated_days_ago: 14,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0003seedmock",
    factors: [
      { code: "QEF", label: "Качество энзимов", value: 90, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 81 },
      { code: "CCF", label: "Контроль концентрации", value: 88, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 79.2 },
      { code: "PCF", label: "Протокол чистоты", value: 85, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 76.5 },
      { code: "TRF", label: "Тепловая резистентность", value: 85, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 76.5 },
      { code: "RF", label: "Поглощающая фракция", value: 85, v_i: 0.9, freshness_di: 14, di_class: "B", contribution: 76.5 },
      { code: "SCIF", label: "Стабильность цепочек", value: 82, v_i: 0.9, freshness_di: 14, di_class: "B", contribution: 73.8 },
      { code: "FRF", label: "Поглощение фрагментов", value: 80, v_i: 0.9, freshness_di: 14, di_class: "C", contribution: 72 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 71.1, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0003seedmock", computed_at: "2026-06-12T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.eurogentec.com" },
  },

  {
    id: "p-004",
    display_name: "JPT Peptide Technologies GmbH",
    role_code: "MANUFACTURER",
    status: "ACTIVE",
    jurisdiction: "Германия (DE)",
    domain: "jpt.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L2",
    score: 64.5,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 90,
    tests_count: 20,
    updated_days_ago: 30,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0004seedmock",
    factors: [
      { code: "QEF", label: "Качество энзимов", value: 85, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 76.5 },
      { code: "TRF", label: "Тепловая резистентность", value: 82, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 73.8 },
      { code: "CCF", label: "Контроль концентрации", value: 82, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 73.8 },
      { code: "PCF", label: "Протокол чистоты", value: 80, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 72 },
      { code: "RF", label: "Поглощающая фракция", value: 80, v_i: 0.9, freshness_di: 30, di_class: "B", contribution: 72 },
      { code: "SCIF", label: "Стабильность цепочек", value: 78, v_i: 0.9, freshness_di: 30, di_class: "B", contribution: 70.2 },
      { code: "FRF", label: "Поглощение фрагментов", value: 75, v_i: 0.9, freshness_di: 30, di_class: "C", contribution: 67.5 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 64.5, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0004seedmock", computed_at: "2026-05-27T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.jpt.com" },
  },

  {
    id: "p-005",
    display_name: "Biosynth AG",
    role_code: "MANUFACTURER",
    status: "ACTIVE",
    jurisdiction: "Швейцария (CH)",
    domain: "biosynth.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L2",
    score: 65.8,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 90,
    tests_count: 25,
    updated_days_ago: 14,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0005seedmock",
    factors: [
      { code: "QEF", label: "Качество энзимов", value: 82, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 73.8 },
      { code: "PCF", label: "Протокол чистоты", value: 80, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 72 },
      { code: "CCF", label: "Контроль концентрации", value: 80, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 72 },
      { code: "SCIF", label: "Стабильность цепочек", value: 78, v_i: 0.9, freshness_di: 14, di_class: "B", contribution: 70.2 },
      { code: "TRF", label: "Тепловая резистентность", value: 78, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 70.2 },
      { code: "RF", label: "Поглощающая фракция", value: 78, v_i: 0.9, freshness_di: 14, di_class: "B", contribution: 70.2 },
      { code: "FRF", label: "Поглощение фрагментов", value: 75, v_i: 0.9, freshness_di: 14, di_class: "C", contribution: 67.5 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 65.8, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0005seedmock", computed_at: "2026-06-12T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.biosynth.com" },
  },

  {
    id: "p-006",
    display_name: "Almac Sciences Ltd",
    role_code: "MANUFACTURER",
    status: "ACTIVE",
    jurisdiction: "Великобритания (GB)",
    domain: "almacgroup.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L2",
    score: 63.5,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 90,
    tests_count: 18,
    updated_days_ago: 30,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0006seedmock",
    factors: [
      { code: "QEF", label: "Качество энзимов", value: 82, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 73.8 },
      { code: "CCF", label: "Контроль концентрации", value: 82, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 73.8 },
      { code: "PCF", label: "Протокол чистоты", value: 80, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 72 },
      { code: "TRF", label: "Тепловая резистентность", value: 80, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 72 },
      { code: "SCIF", label: "Стабильность цепочек", value: 78, v_i: 0.9, freshness_di: 30, di_class: "B", contribution: 70.2 },
      { code: "RF", label: "Поглощающая фракция", value: 78, v_i: 0.9, freshness_di: 30, di_class: "B", contribution: 70.2 },
      { code: "FRF", label: "Поглощение фрагментов", value: 75, v_i: 0.9, freshness_di: 30, di_class: "C", contribution: 67.5 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 63.5, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0006seedmock", computed_at: "2026-05-27T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.almacgroup.com" },
  },

  {
    id: "p-007",
    display_name: "Merck KGaA / Sigma-Aldrich",
    role_code: "MANUFACTURER",
    status: "ACTIVE",
    jurisdiction: "Германия (DE)",
    domain: "sigmaaldrich.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 67.7,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 100,
    tests_count: 50,
    updated_days_ago: 1,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0007seedmock",
    factors: [
      { code: "FRF", label: "Поглощение фрагментов", value: 92, v_i: 0.9, freshness_di: 1, di_class: "C", contribution: 82.8 },
      { code: "RF", label: "Поглощающая фракция", value: 85, v_i: 0.9, freshness_di: 1, di_class: "B", contribution: 76.5 },
      { code: "QEF", label: "Качество энзимов", value: 82, v_i: 0.9, freshness_di: 1, di_class: "A", contribution: 73.8 },
      { code: "SCIF", label: "Стабильность цепочек", value: 80, v_i: 0.9, freshness_di: 1, di_class: "B", contribution: 72 },
      { code: "CCF", label: "Контроль концентрации", value: 80, v_i: 0.9, freshness_di: 1, di_class: "A", contribution: 72 },
      { code: "PCF", label: "Протокол чистоты", value: 78, v_i: 0.9, freshness_di: 1, di_class: "A", contribution: 70.2 },
      { code: "TRF", label: "Тепловая резистентность", value: 75, v_i: 0.9, freshness_di: 1, di_class: "A", contribution: 67.5 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 67.7, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0007seedmock", computed_at: "2026-06-25T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.sigmaaldrich.com" },
  },

  {
    id: "p-008",
    display_name: "Iris Biotech GmbH",
    role_code: "MANUFACTURER",
    status: "ACTIVE",
    jurisdiction: "Германия (DE)",
    domain: "iris-biotech.de",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L2",
    score: 60.1,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 90,
    tests_count: 15,
    updated_days_ago: 30,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0008seedmock",
    factors: [
      { code: "QEF", label: "Качество энзимов", value: 78, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 70.2 },
      { code: "TRF", label: "Тепловая резистентность", value: 78, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 70.2 },
      { code: "CCF", label: "Контроль концентрации", value: 78, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 70.2 },
      { code: "SCIF", label: "Стабильность цепочек", value: 75, v_i: 0.9, freshness_di: 30, di_class: "B", contribution: 67.5 },
      { code: "RF", label: "Поглощающая фракция", value: 75, v_i: 0.9, freshness_di: 30, di_class: "B", contribution: 67.5 },
      { code: "PCF", label: "Протокол чистоты", value: 72, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 64.8 },
      { code: "FRF", label: "Поглощение фрагментов", value: 72, v_i: 0.9, freshness_di: 30, di_class: "C", contribution: 64.8 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 60.1, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0008seedmock", computed_at: "2026-05-27T05:59:11.067Z" },
    ],
    contacts: { website: "https://iris-biotech.de", email: "info@iris-biotech.de" },
  },

  {
    id: "p-009",
    display_name: "Biosyntan GmbH",
    role_code: "MANUFACTURER",
    status: "ACTIVE",
    jurisdiction: "Германия (DE)",
    domain: "biosyntan.de",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L1",
    score: 32.5,
    tier: "Bronze",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 75,
    tests_count: 8,
    updated_days_ago: 90,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0009seedmock",
    factors: [
      { code: "PCF", label: "Протокол чистоты", value: 65, v_i: 0.75, freshness_di: 90, di_class: "A", contribution: 48.8 },
      { code: "TRF", label: "Тепловая резистентность", value: 62, v_i: 0.75, freshness_di: 90, di_class: "A", contribution: 46.5 },
      { code: "FRF", label: "Поглощение фрагментов", value: 60, v_i: 0.75, freshness_di: 90, di_class: "C", contribution: 45 },
      { code: "CCF", label: "Контроль концентрации", value: 58, v_i: 0.75, freshness_di: 90, di_class: "A", contribution: 43.5 },
      { code: "RF", label: "Поглощающая фракция", value: 58, v_i: 0.75, freshness_di: 90, di_class: "B", contribution: 43.5 },
      { code: "SCIF", label: "Стабильность цепочек", value: 55, v_i: 0.75, freshness_di: 90, di_class: "B", contribution: 41.3 },
      { code: "QEF", label: "Качество энзимов", value: 52, v_i: 0.75, freshness_di: 90, di_class: "A", contribution: 39 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 32.5, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0009seedmock", computed_at: "2026-03-28T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.biosyntan.de" },
  },

  {
    id: "p-010",
    display_name: "PepScan sp. z o.o.",
    role_code: "MANUFACTURER",
    status: "ACTIVE",
    jurisdiction: "Польша (PL)",
    domain: "pepscan.eu",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L1",
    score: 32.8,
    tier: "Bronze",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 72,
    tests_count: 6,
    updated_days_ago: 60,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0010seedmock",
    factors: [
      { code: "PCF", label: "Протокол чистоты", value: 60, v_i: 0.75, freshness_di: 60, di_class: "A", contribution: 45 },
      { code: "TRF", label: "Тепловая резистентность", value: 55, v_i: 0.75, freshness_di: 60, di_class: "A", contribution: 41.3 },
      { code: "FRF", label: "Поглощение фрагментов", value: 55, v_i: 0.75, freshness_di: 60, di_class: "C", contribution: 41.3 },
      { code: "CCF", label: "Контроль концентрации", value: 55, v_i: 0.75, freshness_di: 60, di_class: "A", contribution: 41.3 },
      { code: "RF", label: "Поглощающая фракция", value: 55, v_i: 0.75, freshness_di: 60, di_class: "B", contribution: 41.3 },
      { code: "SCIF", label: "Стабильность цепочек", value: 52, v_i: 0.75, freshness_di: 60, di_class: "B", contribution: 39 },
      { code: "QEF", label: "Качество энзимов", value: 50, v_i: 0.75, freshness_di: 60, di_class: "A", contribution: 37.5 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 32.8, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0010seedmock", computed_at: "2026-04-27T05:59:11.067Z" },
    ],
    contacts: { website: "https://pepscan.eu/en/" },
  },

  {
    id: "p-011",
    display_name: "Peptide Protein Research Ltd",
    role_code: "MANUFACTURER",
    status: "ACTIVE",
    jurisdiction: "Великобритания (GB)",
    domain: "ppr.co.uk",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L1",
    score: 31.8,
    tier: "Bronze",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 72,
    tests_count: 5,
    updated_days_ago: 60,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0011seedmock",
    factors: [
      { code: "PCF", label: "Протокол чистоты", value: 58, v_i: 0.75, freshness_di: 60, di_class: "A", contribution: 43.5 },
      { code: "TRF", label: "Тепловая резистентность", value: 55, v_i: 0.75, freshness_di: 60, di_class: "A", contribution: 41.3 },
      { code: "FRF", label: "Поглощение фрагментов", value: 52, v_i: 0.75, freshness_di: 60, di_class: "C", contribution: 39 },
      { code: "QEF", label: "Качество энзимов", value: 50, v_i: 0.75, freshness_di: 60, di_class: "A", contribution: 37.5 },
      { code: "CCF", label: "Контроль концентрации", value: 50, v_i: 0.75, freshness_di: 60, di_class: "A", contribution: 37.5 },
      { code: "RF", label: "Поглощающая фракция", value: 50, v_i: 0.75, freshness_di: 60, di_class: "B", contribution: 37.5 },
      { code: "SCIF", label: "Стабильность цепочек", value: 48, v_i: 0.75, freshness_di: 60, di_class: "B", contribution: 36 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 31.8, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0011seedmock", computed_at: "2026-04-27T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.ppr.co.uk" },
  },

  {
    id: "p-012",
    display_name: "TL Research Ltd",
    role_code: "VENDOR",
    status: "ACTIVE",
    jurisdiction: "Великобритания (GB)",
    domain: "tidelabs.co.uk",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L2",
    score: 46.1,
    tier: "Silver",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 85,
    tests_count: 15,
    updated_days_ago: 7,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0012seedmock",
    factors: [
      { code: "FRF", label: "Поглощение фрагментов", value: 75, v_i: 0.75, freshness_di: 7, di_class: "C", contribution: 56.3 },
      { code: "PCF", label: "Протокол чистоты", value: 65, v_i: 0.75, freshness_di: 7, di_class: "A", contribution: 48.8 },
      { code: "RF", label: "Поглощающая фракция", value: 65, v_i: 0.75, freshness_di: 7, di_class: "B", contribution: 48.8 },
      { code: "CCF", label: "Контроль концентрации", value: 62, v_i: 0.75, freshness_di: 7, di_class: "A", contribution: 46.5 },
      { code: "QEF", label: "Качество энзимов", value: 60, v_i: 0.75, freshness_di: 7, di_class: "A", contribution: 45 },
      { code: "TRF", label: "Тепловая резистентность", value: 58, v_i: 0.75, freshness_di: 7, di_class: "A", contribution: 43.5 },
      { code: "SCIF", label: "Стабильность цепочек", value: 55, v_i: 0.75, freshness_di: 7, di_class: "B", contribution: 41.3 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 46.1, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0012seedmock", computed_at: "2026-06-19T05:59:11.067Z" },
    ],
    contacts: { website: "https://tidelabs.co.uk" },
  },

  {
    id: "p-013",
    display_name: "Peptra Labs",
    role_code: "VENDOR",
    status: "PROVISIONAL",
    jurisdiction: "ЕС (EU)",
    domain: "peptralabs.com",
    isAnchorRole: true,
    verified_legal: false,
    kyb_level: "L0",
    score: 24.7,
    tier: "Bronze",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 65,
    tests_count: 12,
    updated_days_ago: 14,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0013seedmock",
    factors: [
      { code: "FRF", label: "Поглощение фрагментов", value: 60, v_i: 0.55, freshness_di: 14, di_class: "C", contribution: 33 },
      { code: "PCF", label: "Протокол чистоты", value: 58, v_i: 0.55, freshness_di: 14, di_class: "A", contribution: 31.9 },
      { code: "TRF", label: "Тепловая резистентность", value: 52, v_i: 0.55, freshness_di: 14, di_class: "A", contribution: 28.6 },
      { code: "SCIF", label: "Стабильность цепочек", value: 40, v_i: 0.55, freshness_di: 14, di_class: "B", contribution: 22 },
      { code: "RF", label: "Поглощающая фракция", value: 38, v_i: 0.55, freshness_di: 14, di_class: "B", contribution: 20.9 },
      { code: "QEF", label: "Качество энзимов", value: 35, v_i: 0.55, freshness_di: 14, di_class: "A", contribution: 19.3 },
      { code: "CCF", label: "Контроль концентрации", value: 32, v_i: 0.55, freshness_di: 14, di_class: "A", contribution: 17.6 },
    ],
    flags: [
      { id: "f-1", type: 'LEGAL_UNVERIFIED', severity: 'INFO', status: 'OPEN', message: 'Юридическое лицо/юрисдикция не верифицированы публично — требуется KYB', raised_at: '2026-06-01T00:00:00Z' },
    ],
    score_events: [
      { id: 'e-1', score: 24.7, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0013seedmock", computed_at: "2026-06-12T05:59:11.067Z" },
    ],
    provisional_reason: "Юрлицо и юрисдикция публично не раскрыты. Нет impressum/legal notice на сайте. KYB невозможен до раскрытия legal entity. Требуется запросить юридические данные напрямую или через национальный реестр ЕС.",
    contacts: { website: "https://www.peptralabs.com", email: "info@peptralabs.com" },
  },

  {
    id: "p-014",
    display_name: "Baltic BioLabs",
    role_code: "VENDOR",
    status: "PROVISIONAL",
    jurisdiction: "ЕС (EU)",
    domain: "balticbiolabs.eu",
    isAnchorRole: true,
    verified_legal: false,
    kyb_level: "L0",
    score: 19.6,
    tier: "Watch",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 65,
    tests_count: 8,
    updated_days_ago: 30,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0014seedmock",
    factors: [
      { code: "FRF", label: "Поглощение фрагментов", value: 55, v_i: 0.55, freshness_di: 30, di_class: "C", contribution: 30.3 },
      { code: "PCF", label: "Протокол чистоты", value: 50, v_i: 0.55, freshness_di: 30, di_class: "A", contribution: 27.5 },
      { code: "TRF", label: "Тепловая резистентность", value: 40, v_i: 0.55, freshness_di: 30, di_class: "A", contribution: 22 },
      { code: "SCIF", label: "Стабильность цепочек", value: 35, v_i: 0.55, freshness_di: 30, di_class: "B", contribution: 19.3 },
      { code: "RF", label: "Поглощающая фракция", value: 35, v_i: 0.55, freshness_di: 30, di_class: "B", contribution: 19.3 },
      { code: "QEF", label: "Качество энзимов", value: 32, v_i: 0.55, freshness_di: 30, di_class: "A", contribution: 17.6 },
      { code: "CCF", label: "Контроль концентрации", value: 30, v_i: 0.55, freshness_di: 30, di_class: "A", contribution: 16.5 },
    ],
    flags: [
      { id: "f-1", type: 'LEGAL_UNVERIFIED', severity: 'INFO', status: 'OPEN', message: 'Юридическое лицо/юрисдикция не верифицированы публично — требуется KYB', raised_at: '2026-06-01T00:00:00Z' },
      { id: "f-2", type: 'REGULATORY_RISK', severity: 'WARNING', status: 'OPEN', message: 'Продажа EMA/FDA-регулируемых молекул под видом RUO — регуляторный риск', raised_at: '2026-06-01T00:00:00Z' },
    ],
    score_events: [
      { id: 'e-1', score: 19.6, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0014seedmock", computed_at: "2026-05-27T05:59:11.067Z" },
    ],
    provisional_reason: "Юрлицо; юрисдикция; рег.номер не раскрыты. Маркетинговые claims без подтверждающей документации ('GMP'; 'ISO-certified labs' без указания lab-name). Обязательна ручная KYB-проверка перед любой публикацией.",
    contacts: { website: "https://balticbiolabs.eu" },
  },

  {
    id: "p-015",
    display_name: "Research Peptides Europe",
    role_code: "VENDOR",
    status: "PROVISIONAL",
    jurisdiction: "ЕС (EU)",
    domain: "researchpeptideseurope.com",
    isAnchorRole: true,
    verified_legal: false,
    kyb_level: "L0",
    score: 15.2,
    tier: "Watch",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 65,
    tests_count: 10,
    updated_days_ago: 90,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0015seedmock",
    factors: [
      { code: "PCF", label: "Протокол чистоты", value: 55, v_i: 0.55, freshness_di: 90, di_class: "A", contribution: 30.3 },
      { code: "FRF", label: "Поглощение фрагментов", value: 55, v_i: 0.55, freshness_di: 90, di_class: "C", contribution: 30.3 },
      { code: "TRF", label: "Тепловая резистентность", value: 42, v_i: 0.55, freshness_di: 90, di_class: "A", contribution: 23.1 },
      { code: "SCIF", label: "Стабильность цепочек", value: 38, v_i: 0.55, freshness_di: 90, di_class: "B", contribution: 20.9 },
      { code: "RF", label: "Поглощающая фракция", value: 38, v_i: 0.55, freshness_di: 90, di_class: "B", contribution: 20.9 },
      { code: "QEF", label: "Качество энзимов", value: 35, v_i: 0.55, freshness_di: 90, di_class: "A", contribution: 19.3 },
      { code: "CCF", label: "Контроль концентрации", value: 32, v_i: 0.55, freshness_di: 90, di_class: "A", contribution: 17.6 },
    ],
    flags: [
      { id: "f-1", type: 'LEGAL_UNVERIFIED', severity: 'INFO', status: 'OPEN', message: 'Юридическое лицо/юрисдикция не верифицированы публично — требуется KYB', raised_at: '2026-06-01T00:00:00Z' },
    ],
    score_events: [
      { id: 'e-1', score: 15.2, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0015seedmock", computed_at: "2026-03-28T05:59:11.067Z" },
    ],
    provisional_reason: "Юрлицо; юрисдикция; рег.номер не раскрыты. EU-доставка; HPLC/LC-MS/FTIR + эндотоксины + биобёрден (USP) + тяжёлые металлы. Юрлицо не раскрыто — блокирует ACTIVE-статус.",
    contacts: { website: "https://researchpeptideseurope.com", email: "info@researchpeptideseurope.com" },
  },

  {
    id: "p-016",
    display_name: "ELYVERA Research Peptides",
    role_code: "VENDOR",
    status: "PROVISIONAL",
    jurisdiction: "Австрия (AT)",
    domain: "europeptides.de",
    isAnchorRole: true,
    verified_legal: false,
    kyb_level: "L0",
    score: 19.1,
    tier: "Watch",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 65,
    tests_count: 8,
    updated_days_ago: 30,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0016seedmock",
    factors: [
      { code: "FRF", label: "Поглощение фрагментов", value: 52, v_i: 0.55, freshness_di: 30, di_class: "C", contribution: 28.6 },
      { code: "PCF", label: "Протокол чистоты", value: 50, v_i: 0.55, freshness_di: 30, di_class: "A", contribution: 27.5 },
      { code: "TRF", label: "Тепловая резистентность", value: 45, v_i: 0.55, freshness_di: 30, di_class: "A", contribution: 24.8 },
      { code: "CVF", label: "Валидация компонентов", value: 42, v_i: 0.55, freshness_di: 30, di_class: "D", contribution: 23.1 },
      { code: "SCIF", label: "Стабильность цепочек", value: 32, v_i: 0.55, freshness_di: 30, di_class: "B", contribution: 17.6 },
      { code: "QEF", label: "Качество энзимов", value: 30, v_i: 0.55, freshness_di: 30, di_class: "A", contribution: 16.5 },
      { code: "RF", label: "Поглощающая фракция", value: 30, v_i: 0.55, freshness_di: 30, di_class: "B", contribution: 16.5 },
      { code: "CCF", label: "Контроль концентрации", value: 28, v_i: 0.55, freshness_di: 30, di_class: "A", contribution: 15.4 },
    ],
    flags: [
      { id: "f-1", type: 'LEGAL_UNVERIFIED', severity: 'INFO', status: 'OPEN', message: 'Юридическое лицо/юрисдикция не верифицированы публично — требуется KYB', raised_at: '2026-06-01T00:00:00Z' },
      { id: "f-2", type: 'REGULATORY_RISK', severity: 'WARNING', status: 'OPEN', message: 'Продажа EMA/FDA-регулируемых молекул под видом RUO — регуляторный риск', raised_at: '2026-06-01T00:00:00Z' },
    ],
    score_events: [
      { id: 'e-1', score: 19.1, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0016seedmock", computed_at: "2026-05-27T05:59:11.067Z" },
    ],
    provisional_reason: "Austria-based supplier согласно Trustpilot (29 отзывов); юрисдикция скорректирована AT (domain .de вводит в заблуждение). Австрийский Firmenbuch номер не найден публично. KYB gap. domain .de НЕ подтверждает DE-регистрацию.",
    contacts: { website: "https://europeptides.de" },
  },

  {
    id: "p-017",
    display_name: "Imperial Sciences Ltd",
    role_code: "VENDOR",
    status: "ACTIVE",
    jurisdiction: "Великобритания (GB)",
    domain: "imperialsciences.co.uk",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L2",
    score: 39.8,
    tier: "Bronze",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 85,
    tests_count: 10,
    updated_days_ago: 7,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0017seedmock",
    factors: [
      { code: "FRF", label: "Поглощение фрагментов", value: 70, v_i: 0.75, freshness_di: 7, di_class: "C", contribution: 52.5 },
      { code: "PCF", label: "Протокол чистоты", value: 55, v_i: 0.75, freshness_di: 7, di_class: "A", contribution: 41.3 },
      { code: "QEF", label: "Качество энзимов", value: 52, v_i: 0.75, freshness_di: 7, di_class: "A", contribution: 39 },
      { code: "TRF", label: "Тепловая резистентность", value: 48, v_i: 0.75, freshness_di: 7, di_class: "A", contribution: 36 },
      { code: "SCIF", label: "Стабильность цепочек", value: 40, v_i: 0.75, freshness_di: 7, di_class: "B", contribution: 30 },
      { code: "CCF", label: "Контроль концентрации", value: 32, v_i: 0.75, freshness_di: 7, di_class: "A", contribution: 24 },
      { code: "RF", label: "Поглощающая фракция", value: 32, v_i: 0.75, freshness_di: 7, di_class: "B", contribution: 24 },
    ],
    flags: [
      { id: "f-1", type: 'REGULATORY_RISK', severity: 'WARNING', status: 'OPEN', message: 'Продажа EMA/FDA-регулируемых молекул под видом RUO — регуляторный риск', raised_at: '2026-06-01T00:00:00Z' },
    ],
    score_events: [
      { id: 'e-1', score: 39.8, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0017seedmock", computed_at: "2026-06-19T05:59:11.067Z" },
    ],
    contacts: { website: "https://imperialsciences.co.uk" },
  },

  {
    id: "p-018",
    display_name: "Peptidos.eu",
    role_code: "VENDOR",
    status: "PROVISIONAL",
    jurisdiction: "ЕС (EU)",
    domain: "peptidos.eu",
    isAnchorRole: true,
    verified_legal: false,
    kyb_level: "L0",
    score: 24.8,
    tier: "Bronze",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 65,
    tests_count: 8,
    updated_days_ago: 14,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0018seedmock",
    factors: [
      { code: "FRF", label: "Поглощение фрагментов", value: 60, v_i: 0.55, freshness_di: 14, di_class: "C", contribution: 33 },
      { code: "SCIF", label: "Стабильность цепочек", value: 52, v_i: 0.55, freshness_di: 14, di_class: "B", contribution: 28.6 },
      { code: "PCF", label: "Протокол чистоты", value: 45, v_i: 0.55, freshness_di: 14, di_class: "A", contribution: 24.8 },
      { code: "TRF", label: "Тепловая резистентность", value: 45, v_i: 0.55, freshness_di: 14, di_class: "A", contribution: 24.8 },
      { code: "QEF", label: "Качество энзимов", value: 42, v_i: 0.55, freshness_di: 14, di_class: "A", contribution: 23.1 },
      { code: "RF", label: "Поглощающая фракция", value: 42, v_i: 0.55, freshness_di: 14, di_class: "B", contribution: 23.1 },
      { code: "CCF", label: "Контроль концентрации", value: 40, v_i: 0.55, freshness_di: 14, di_class: "A", contribution: 22 },
    ],
    flags: [
      { id: "f-1", type: 'LEGAL_UNVERIFIED', severity: 'INFO', status: 'OPEN', message: 'Юридическое лицо/юрисдикция не верифицированы публично — требуется KYB', raised_at: '2026-06-01T00:00:00Z' },
    ],
    score_events: [
      { id: 'e-1', score: 24.8, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0018seedmock", computed_at: "2026-06-12T05:59:11.067Z" },
    ],
    provisional_reason: "Юрлицо и национальная юрисдикция не раскрыты публично. Нет impressum. Trustpilot: 5 отзывов — выборка мала. KYB требуется через национальный реестр ЕС.",
    contacts: { website: "https://peptidos.eu" },
  },

  {
    id: "p-019",
    display_name: "Swiss Chem Labs",
    role_code: "RETAILER",
    status: "PROVISIONAL",
    jurisdiction: "Швейцария (CH)",
    domain: "swisschemss.com",
    isAnchorRole: true,
    verified_legal: false,
    kyb_level: "L0",
    score: 18.4,
    tier: "Watch",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 65,
    tests_count: 5,
    updated_days_ago: 30,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0019seedmock",
    factors: [
      { code: "PCF", label: "Протокол чистоты", value: 52, v_i: 0.55, freshness_di: 30, di_class: "A", contribution: 28.6 },
      { code: "FRF", label: "Поглощение фрагментов", value: 45, v_i: 0.55, freshness_di: 30, di_class: "C", contribution: 24.8 },
      { code: "TRF", label: "Тепловая резистентность", value: 42, v_i: 0.55, freshness_di: 30, di_class: "A", contribution: 23.1 },
      { code: "QEF", label: "Качество энзимов", value: 30, v_i: 0.55, freshness_di: 30, di_class: "A", contribution: 16.5 },
      { code: "SCIF", label: "Стабильность цепочек", value: 30, v_i: 0.55, freshness_di: 30, di_class: "B", contribution: 16.5 },
      { code: "CCF", label: "Контроль концентрации", value: 28, v_i: 0.55, freshness_di: 30, di_class: "A", contribution: 15.4 },
      { code: "RF", label: "Поглощающая фракция", value: 28, v_i: 0.55, freshness_di: 30, di_class: "B", contribution: 15.4 },
    ],
    flags: [
      { id: "f-1", type: 'LEGAL_UNVERIFIED', severity: 'INFO', status: 'OPEN', message: 'Юридическое лицо/юрисдикция не верифицированы публично — требуется KYB', raised_at: '2026-06-01T00:00:00Z' },
    ],
    score_events: [
      { id: 'e-1', score: 18.4, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0019seedmock", computed_at: "2026-05-27T05:59:11.067Z" },
    ],
    provisional_reason: "Swiss-бренд без верификации CH-регистрации (ZEFIX/Moneyhouse поиск не дал результата). Юрлицо не установлено. Смешанный ассортимент (пептиды + SARMs). KYB через eCH-Registry обязателен.",
    contacts: { website: "https://swisschemss.com" },
  },

  {
    id: "p-020",
    display_name: "Eurofins BioPharma Product Testing",
    role_code: "LABORATORY",
    status: "ACTIVE",
    jurisdiction: "Люксембург (LU)",
    domain: "eurofins.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 75.4,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 100,
    tests_count: 100,
    updated_days_ago: 3,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0020seedmock",
    factors: [
      { code: "QEF", label: "Качество энзимов", value: 92, v_i: 0.9, freshness_di: 3, di_class: "A", contribution: 82.8 },
      { code: "TRF", label: "Тепловая резистентность", value: 90, v_i: 0.9, freshness_di: 3, di_class: "A", contribution: 81 },
      { code: "FRF", label: "Поглощение фрагментов", value: 90, v_i: 0.9, freshness_di: 3, di_class: "C", contribution: 81 },
      { code: "CCF", label: "Контроль концентрации", value: 90, v_i: 0.9, freshness_di: 3, di_class: "A", contribution: 81 },
      { code: "PCF", label: "Протокол чистоты", value: 88, v_i: 0.9, freshness_di: 3, di_class: "A", contribution: 79.2 },
      { code: "RF", label: "Поглощающая фракция", value: 88, v_i: 0.9, freshness_di: 3, di_class: "B", contribution: 79.2 },
      { code: "SCIF", label: "Стабильность цепочек", value: 85, v_i: 0.9, freshness_di: 3, di_class: "B", contribution: 76.5 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 75.4, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0020seedmock", computed_at: "2026-06-23T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.eurofins.com/biopharma-services/" },
  },

  {
    id: "p-021",
    display_name: "SGS SA Life Science Services",
    role_code: "LABORATORY",
    status: "ACTIVE",
    jurisdiction: "Швейцария (CH)",
    domain: "sgs.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 70.4,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 100,
    tests_count: 80,
    updated_days_ago: 7,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0021seedmock",
    factors: [
      { code: "QEF", label: "Качество энзимов", value: 88, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 79.2 },
      { code: "TRF", label: "Тепловая резистентность", value: 85, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 76.5 },
      { code: "FRF", label: "Поглощение фрагментов", value: 85, v_i: 0.9, freshness_di: 7, di_class: "C", contribution: 76.5 },
      { code: "CCF", label: "Контроль концентрации", value: 85, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 76.5 },
      { code: "PCF", label: "Протокол чистоты", value: 82, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 73.8 },
      { code: "RF", label: "Поглощающая фракция", value: 82, v_i: 0.9, freshness_di: 7, di_class: "B", contribution: 73.8 },
      { code: "SCIF", label: "Стабильность цепочек", value: 80, v_i: 0.9, freshness_di: 7, di_class: "B", contribution: 72 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 70.4, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0021seedmock", computed_at: "2026-06-19T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.sgs.com/en/industries/life-science" },
  },

  {
    id: "p-022",
    display_name: "LGC Group Ltd",
    role_code: "LABORATORY",
    status: "ACTIVE",
    jurisdiction: "Великобритания (GB)",
    domain: "lgcgroup.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 68.9,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 97,
    tests_count: 60,
    updated_days_ago: 14,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0022seedmock",
    factors: [
      { code: "QEF", label: "Качество энзимов", value: 88, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 79.2 },
      { code: "CCF", label: "Контроль концентрации", value: 85, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 76.5 },
      { code: "PCF", label: "Протокол чистоты", value: 82, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 73.8 },
      { code: "TRF", label: "Тепловая резистентность", value: 82, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 73.8 },
      { code: "RF", label: "Поглощающая фракция", value: 82, v_i: 0.9, freshness_di: 14, di_class: "B", contribution: 73.8 },
      { code: "SCIF", label: "Стабильность цепочек", value: 80, v_i: 0.9, freshness_di: 14, di_class: "B", contribution: 72 },
      { code: "FRF", label: "Поглощение фрагментов", value: 80, v_i: 0.9, freshness_di: 14, di_class: "C", contribution: 72 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 68.9, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0022seedmock", computed_at: "2026-06-12T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.lgcgroup.com" },
  },

  {
    id: "p-023",
    display_name: "Charles River Laboratories EU",
    role_code: "LABORATORY",
    status: "ACTIVE",
    jurisdiction: "Великобритания (GB)",
    domain: "criver.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 65.9,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 100,
    tests_count: 40,
    updated_days_ago: 14,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0023seedmock",
    factors: [
      { code: "TRF", label: "Тепловая резистентность", value: 85, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 76.5 },
      { code: "QEF", label: "Качество энзимов", value: 82, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 73.8 },
      { code: "PCF", label: "Протокол чистоты", value: 78, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 70.2 },
      { code: "SCIF", label: "Стабильность цепочек", value: 78, v_i: 0.9, freshness_di: 14, di_class: "B", contribution: 70.2 },
      { code: "FRF", label: "Поглощение фрагментов", value: 78, v_i: 0.9, freshness_di: 14, di_class: "C", contribution: 70.2 },
      { code: "CCF", label: "Контроль концентрации", value: 78, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 70.2 },
      { code: "RF", label: "Поглощающая фракция", value: 78, v_i: 0.9, freshness_di: 14, di_class: "B", contribution: 70.2 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 65.9, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0023seedmock", computed_at: "2026-06-12T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.criver.com" },
  },

  {
    id: "p-024",
    display_name: "Labcorp Drug Development",
    role_code: "LABORATORY",
    status: "ACTIVE",
    jurisdiction: "Великобритания (GB)",
    domain: "labcorp.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 66.6,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 100,
    tests_count: 35,
    updated_days_ago: 14,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0024seedmock",
    factors: [
      { code: "QEF", label: "Качество энзимов", value: 84, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 75.6 },
      { code: "PCF", label: "Протокол чистоты", value: 80, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 72 },
      { code: "TRF", label: "Тепловая резистентность", value: 80, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 72 },
      { code: "CCF", label: "Контроль концентрации", value: 80, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 72 },
      { code: "SCIF", label: "Стабильность цепочек", value: 78, v_i: 0.9, freshness_di: 14, di_class: "B", contribution: 70.2 },
      { code: "FRF", label: "Поглощение фрагментов", value: 78, v_i: 0.9, freshness_di: 14, di_class: "C", contribution: 70.2 },
      { code: "RF", label: "Поглощающая фракция", value: 78, v_i: 0.9, freshness_di: 14, di_class: "B", contribution: 70.2 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 66.6, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0024seedmock", computed_at: "2026-06-12T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.labcorp.com/drug-development" },
  },

  {
    id: "p-025",
    display_name: "Intertek Group plc",
    role_code: "LABORATORY",
    status: "ACTIVE",
    jurisdiction: "Великобритания (GB)",
    domain: "intertek.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 64.1,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 100,
    tests_count: 30,
    updated_days_ago: 7,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0025seedmock",
    factors: [
      { code: "TRF", label: "Тепловая резистентность", value: 82, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 73.8 },
      { code: "QEF", label: "Качество энзимов", value: 80, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 72 },
      { code: "SCIF", label: "Стабильность цепочек", value: 75, v_i: 0.9, freshness_di: 7, di_class: "B", contribution: 67.5 },
      { code: "FRF", label: "Поглощение фрагментов", value: 75, v_i: 0.9, freshness_di: 7, di_class: "C", contribution: 67.5 },
      { code: "CCF", label: "Контроль концентрации", value: 75, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 67.5 },
      { code: "RF", label: "Поглощающая фракция", value: 75, v_i: 0.9, freshness_di: 7, di_class: "B", contribution: 67.5 },
      { code: "PCF", label: "Протокол чистоты", value: 72, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 64.8 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 64.1, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0025seedmock", computed_at: "2026-06-19T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.intertek.com" },
  },

  {
    id: "p-026",
    display_name: "SYNLAB Analytics & Services GmbH",
    role_code: "LABORATORY",
    status: "ACTIVE",
    jurisdiction: "Германия (DE)",
    domain: "synlab.de",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L2",
    score: 49.1,
    tier: "Silver",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 88,
    tests_count: 25,
    updated_days_ago: 14,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0026seedmock",
    factors: [
      { code: "QEF", label: "Качество энзимов", value: 75, v_i: 0.75, freshness_di: 14, di_class: "A", contribution: 56.3 },
      { code: "TRF", label: "Тепловая резистентность", value: 72, v_i: 0.75, freshness_di: 14, di_class: "A", contribution: 54 },
      { code: "CCF", label: "Контроль концентрации", value: 72, v_i: 0.75, freshness_di: 14, di_class: "A", contribution: 54 },
      { code: "PCF", label: "Протокол чистоты", value: 70, v_i: 0.75, freshness_di: 14, di_class: "A", contribution: 52.5 },
      { code: "FRF", label: "Поглощение фрагментов", value: 70, v_i: 0.75, freshness_di: 14, di_class: "C", contribution: 52.5 },
      { code: "RF", label: "Поглощающая фракция", value: 70, v_i: 0.75, freshness_di: 14, di_class: "B", contribution: 52.5 },
      { code: "SCIF", label: "Стабильность цепочек", value: 68, v_i: 0.75, freshness_di: 14, di_class: "B", contribution: 51 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 49.1, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0026seedmock", computed_at: "2026-06-12T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.synlab.de" },
  },

  {
    id: "p-027",
    display_name: "GALAB Laboratories GmbH",
    role_code: "LABORATORY",
    status: "ACTIVE",
    jurisdiction: "Германия (DE)",
    domain: "galab.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L2",
    score: 45.4,
    tier: "Silver",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 88,
    tests_count: 20,
    updated_days_ago: 14,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0027seedmock",
    factors: [
      { code: "QEF", label: "Качество энзимов", value: 70, v_i: 0.75, freshness_di: 14, di_class: "A", contribution: 52.5 },
      { code: "CCF", label: "Контроль концентрации", value: 68, v_i: 0.75, freshness_di: 14, di_class: "A", contribution: 51 },
      { code: "PCF", label: "Протокол чистоты", value: 65, v_i: 0.75, freshness_di: 14, di_class: "A", contribution: 48.8 },
      { code: "TRF", label: "Тепловая резистентность", value: 65, v_i: 0.75, freshness_di: 14, di_class: "A", contribution: 48.8 },
      { code: "FRF", label: "Поглощение фрагментов", value: 65, v_i: 0.75, freshness_di: 14, di_class: "C", contribution: 48.8 },
      { code: "RF", label: "Поглощающая фракция", value: 65, v_i: 0.75, freshness_di: 14, di_class: "B", contribution: 48.8 },
      { code: "SCIF", label: "Стабильность цепочек", value: 62, v_i: 0.75, freshness_di: 14, di_class: "B", contribution: 46.5 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 45.4, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0027seedmock", computed_at: "2026-06-12T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.galab.com", email: "info@galab.com" },
  },

  {
    id: "p-028",
    display_name: "Janoshik Analytical",
    role_code: "LABORATORY",
    status: "ACTIVE",
    jurisdiction: "Чехия (CZ)",
    domain: "janoshik.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L1",
    score: 33.7,
    tier: "Bronze",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 72,
    tests_count: 100,
    updated_days_ago: 1,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0028seedmock",
    factors: [
      { code: "TRF", label: "Тепловая резистентность", value: 72, v_i: 0.75, freshness_di: 1, di_class: "A", contribution: 54 },
      { code: "FRF", label: "Поглощение фрагментов", value: 72, v_i: 0.75, freshness_di: 1, di_class: "C", contribution: 54 },
      { code: "PCF", label: "Протокол чистоты", value: 55, v_i: 0.75, freshness_di: 1, di_class: "A", contribution: 41.3 },
      { code: "CVF", label: "Валидация компонентов", value: 55, v_i: 0.75, freshness_di: 1, di_class: "D", contribution: 41.3 },
      { code: "SCIF", label: "Стабильность цепочек", value: 42, v_i: 0.75, freshness_di: 1, di_class: "B", contribution: 31.5 },
      { code: "QEF", label: "Качество энзимов", value: 30, v_i: 0.75, freshness_di: 1, di_class: "A", contribution: 22.5 },
      { code: "RF", label: "Поглощающая фракция", value: 30, v_i: 0.75, freshness_di: 1, di_class: "B", contribution: 22.5 },
      { code: "CCF", label: "Контроль концентрации", value: 25, v_i: 0.75, freshness_di: 1, di_class: "A", contribution: 18.8 },
    ],
    flags: [
      { id: "f-1", type: 'DATA_INCIDENT', severity: 'WARNING', status: 'MONITORING', message: 'Утечка данных клиентов (февраль 2026); лаборатория не ISO/IEC 17025 — COA не принимаются FDA/EMA', raised_at: '2026-02-01T00:00:00Z' },
    ],
    score_events: [
      { id: 'e-1', score: 33.7, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0028seedmock", computed_at: "2026-06-25T05:59:11.067Z" },
    ],
    contacts: { website: "https://janoshik.com" },
  },

  {
    id: "p-029",
    display_name: "PeptideVerify",
    role_code: "LABORATORY",
    status: "PROVISIONAL",
    jurisdiction: "Великобритания (GB)",
    domain: "peptideverify.co.uk",
    isAnchorRole: true,
    verified_legal: false,
    kyb_level: "L0",
    score: 20.6,
    tier: "Bronze",
    dominant_factor: 'PCF',
    is_balanced: false,
    trust_ceiling: 65,
    tests_count: 30,
    updated_days_ago: 30,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0029seedmock",
    factors: [
      { code: "PCF", label: "Протокол чистоты", value: 55, v_i: 0.55, freshness_di: 30, di_class: "A", contribution: 30.3 },
      { code: "FRF", label: "Поглощение фрагментов", value: 50, v_i: 0.55, freshness_di: 30, di_class: "C", contribution: 27.5 },
      { code: "TRF", label: "Тепловая резистентность", value: 48, v_i: 0.55, freshness_di: 30, di_class: "A", contribution: 26.4 },
      { code: "RF", label: "Поглощающая фракция", value: 40, v_i: 0.55, freshness_di: 30, di_class: "B", contribution: 22 },
      { code: "QEF", label: "Качество энзимов", value: 35, v_i: 0.55, freshness_di: 30, di_class: "A", contribution: 19.3 },
      { code: "SCIF", label: "Стабильность цепочек", value: 35, v_i: 0.55, freshness_di: 30, di_class: "B", contribution: 19.3 },
      { code: "CCF", label: "Контроль концентрации", value: 32, v_i: 0.55, freshness_di: 30, di_class: "A", contribution: 17.6 },
    ],
    flags: [
      { id: "f-1", type: 'LEGAL_UNVERIFIED', severity: 'INFO', status: 'OPEN', message: 'Юридическое лицо/юрисдикция не верифицированы публично — требуется KYB', raised_at: '2026-06-01T00:00:00Z' },
    ],
    score_events: [
      { id: 'e-1', score: 20.6, dominant_factor: 'PCF', algo_version: 'v2.6.0', anchor_hash: "0x0029seedmock", computed_at: "2026-05-27T05:59:11.067Z" },
    ],
    provisional_reason: "UK тест-сервис для RUO пептидов с QR-верифицированными COA. Юрлицо и ISO/UKAS аккредитация не верифицированы публично. KYB через Companies House UK обязателен.",
    contacts: { website: "https://www.peptideverify.co.uk" },
  },

  {
    id: "p-030",
    display_name: "Cambridge Bioscience Ltd",
    role_code: "DISTRIBUTOR",
    status: "ACTIVE",
    jurisdiction: "Великобритания (GB)",
    domain: "bioscience.co.uk",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 68.2,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 95,
    tests_count: 10,
    updated_days_ago: 7,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0030seedmock",
    factors: [
      { code: "TRF", label: "Тепловая резистентность", value: 85, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 76.5 },
      { code: "PCF", label: "Протокол чистоты", value: 78, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 70.2 },
      { code: "FRF", label: "Поглощение фрагментов", value: 78, v_i: 0.9, freshness_di: 7, di_class: "C", contribution: 70.2 },
      { code: "CCF", label: "Контроль концентрации", value: 78, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 70.2 },
      { code: "RF", label: "Поглощающая фракция", value: 78, v_i: 0.9, freshness_di: 7, di_class: "B", contribution: 70.2 },
      { code: "SCIF", label: "Стабильность цепочек", value: 76, v_i: 0.9, freshness_di: 7, di_class: "B", contribution: 68.4 },
      { code: "QEF", label: "Качество энзимов", value: 72, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 64.8 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 68.2, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0030seedmock", computed_at: "2026-06-19T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.bioscience.co.uk" },
  },

  {
    id: "p-031",
    display_name: "Bio-Techne Ltd / R&D Systems",
    role_code: "DISTRIBUTOR",
    status: "ACTIVE",
    jurisdiction: "Великобритания (GB)",
    domain: "bio-techne.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 65.2,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 100,
    tests_count: 8,
    updated_days_ago: 7,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0031seedmock",
    factors: [
      { code: "TRF", label: "Тепловая резистентность", value: 80, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 72 },
      { code: "FRF", label: "Поглощение фрагментов", value: 80, v_i: 0.9, freshness_di: 7, di_class: "C", contribution: 72 },
      { code: "PCF", label: "Протокол чистоты", value: 75, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 67.5 },
      { code: "CCF", label: "Контроль концентрации", value: 75, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 67.5 },
      { code: "RF", label: "Поглощающая фракция", value: 75, v_i: 0.9, freshness_di: 7, di_class: "B", contribution: 67.5 },
      { code: "SCIF", label: "Стабильность цепочек", value: 72, v_i: 0.9, freshness_di: 7, di_class: "B", contribution: 64.8 },
      { code: "QEF", label: "Качество энзимов", value: 70, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 63 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 65.2, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0031seedmock", computed_at: "2026-06-19T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.bio-techne.com" },
  },

  {
    id: "p-032",
    display_name: "Europa Biosite B.V.",
    role_code: "DISTRIBUTOR",
    status: "ACTIVE",
    jurisdiction: "Нидерланды (NL)",
    domain: "europabiosite.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L2",
    score: 48.3,
    tier: "Silver",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 88,
    tests_count: 5,
    updated_days_ago: 14,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0032seedmock",
    factors: [
      { code: "TRF", label: "Тепловая резистентность", value: 72, v_i: 0.75, freshness_di: 14, di_class: "A", contribution: 54 },
      { code: "PCF", label: "Протокол чистоты", value: 68, v_i: 0.75, freshness_di: 14, di_class: "A", contribution: 51 },
      { code: "FRF", label: "Поглощение фрагментов", value: 68, v_i: 0.75, freshness_di: 14, di_class: "C", contribution: 51 },
      { code: "CCF", label: "Контроль концентрации", value: 68, v_i: 0.75, freshness_di: 14, di_class: "A", contribution: 51 },
      { code: "QEF", label: "Качество энзимов", value: 65, v_i: 0.75, freshness_di: 14, di_class: "A", contribution: 48.8 },
      { code: "SCIF", label: "Стабильность цепочек", value: 65, v_i: 0.75, freshness_di: 14, di_class: "B", contribution: 48.8 },
      { code: "RF", label: "Поглощающая фракция", value: 65, v_i: 0.75, freshness_di: 14, di_class: "B", contribution: 48.8 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 48.3, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0032seedmock", computed_at: "2026-06-12T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.europabiosite.com" },
  },

  {
    id: "p-033",
    display_name: "Biomol GmbH",
    role_code: "DISTRIBUTOR",
    status: "ACTIVE",
    jurisdiction: "Германия (DE)",
    domain: "biomol.de",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L2",
    score: 44.1,
    tier: "Silver",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 85,
    tests_count: 5,
    updated_days_ago: 30,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0033seedmock",
    factors: [
      { code: "TRF", label: "Тепловая резистентность", value: 70, v_i: 0.75, freshness_di: 30, di_class: "A", contribution: 52.5 },
      { code: "QEF", label: "Качество энзимов", value: 65, v_i: 0.75, freshness_di: 30, di_class: "A", contribution: 48.8 },
      { code: "PCF", label: "Протокол чистоты", value: 65, v_i: 0.75, freshness_di: 30, di_class: "A", contribution: 48.8 },
      { code: "FRF", label: "Поглощение фрагментов", value: 65, v_i: 0.75, freshness_di: 30, di_class: "C", contribution: 48.8 },
      { code: "SCIF", label: "Стабильность цепочек", value: 62, v_i: 0.75, freshness_di: 30, di_class: "B", contribution: 46.5 },
      { code: "CCF", label: "Контроль концентрации", value: 62, v_i: 0.75, freshness_di: 30, di_class: "A", contribution: 46.5 },
      { code: "RF", label: "Поглощающая фракция", value: 62, v_i: 0.75, freshness_di: 30, di_class: "B", contribution: 46.5 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 44.1, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0033seedmock", computed_at: "2026-05-27T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.biomol.de" },
  },

  {
    id: "p-034",
    display_name: "Carl Roth GmbH + Co. KG",
    role_code: "DISTRIBUTOR",
    status: "ACTIVE",
    jurisdiction: "Германия (DE)",
    domain: "carlroth.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L2",
    score: 45.8,
    tier: "Silver",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 88,
    tests_count: 5,
    updated_days_ago: 14,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0034seedmock",
    factors: [
      { code: "FRF", label: "Поглощение фрагментов", value: 72, v_i: 0.75, freshness_di: 14, di_class: "C", contribution: 54 },
      { code: "RF", label: "Поглощающая фракция", value: 68, v_i: 0.75, freshness_di: 14, di_class: "B", contribution: 51 },
      { code: "SCIF", label: "Стабильность цепочек", value: 65, v_i: 0.75, freshness_di: 14, di_class: "B", contribution: 48.8 },
      { code: "TRF", label: "Тепловая резистентность", value: 65, v_i: 0.75, freshness_di: 14, di_class: "A", contribution: 48.8 },
      { code: "CCF", label: "Контроль концентрации", value: 65, v_i: 0.75, freshness_di: 14, di_class: "A", contribution: 48.8 },
      { code: "QEF", label: "Качество энзимов", value: 62, v_i: 0.75, freshness_di: 14, di_class: "A", contribution: 46.5 },
      { code: "PCF", label: "Протокол чистоты", value: 60, v_i: 0.75, freshness_di: 14, di_class: "A", contribution: 45 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 45.8, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0034seedmock", computed_at: "2026-06-12T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.carlroth.com" },
  },

  {
    id: "p-035",
    display_name: "Nordic BioSite AB",
    role_code: "DISTRIBUTOR",
    status: "ACTIVE",
    jurisdiction: "Швеция (SE)",
    domain: "nordisk.eu",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L2",
    score: 43.1,
    tier: "Silver",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 85,
    tests_count: 3,
    updated_days_ago: 30,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0035seedmock",
    factors: [
      { code: "TRF", label: "Тепловая резистентность", value: 68, v_i: 0.75, freshness_di: 30, di_class: "A", contribution: 51 },
      { code: "PCF", label: "Протокол чистоты", value: 62, v_i: 0.75, freshness_di: 30, di_class: "A", contribution: 46.5 },
      { code: "FRF", label: "Поглощение фрагментов", value: 62, v_i: 0.75, freshness_di: 30, di_class: "C", contribution: 46.5 },
      { code: "CCF", label: "Контроль концентрации", value: 62, v_i: 0.75, freshness_di: 30, di_class: "A", contribution: 46.5 },
      { code: "QEF", label: "Качество энзимов", value: 60, v_i: 0.75, freshness_di: 30, di_class: "A", contribution: 45 },
      { code: "SCIF", label: "Стабильность цепочек", value: 60, v_i: 0.75, freshness_di: 30, di_class: "B", contribution: 45 },
      { code: "RF", label: "Поглощающая фракция", value: 60, v_i: 0.75, freshness_di: 30, di_class: "B", contribution: 45 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 43.1, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0035seedmock", computed_at: "2026-05-27T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.nordisk.eu" },
  },

  {
    id: "p-036",
    display_name: "Bio-Connect B.V.",
    role_code: "DISTRIBUTOR",
    status: "ACTIVE",
    jurisdiction: "Нидерланды (NL)",
    domain: "bio-connect.nl",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L1",
    score: 37.3,
    tier: "Bronze",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 72,
    tests_count: 3,
    updated_days_ago: 30,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0036seedmock",
    factors: [
      { code: "TRF", label: "Тепловая резистентность", value: 60, v_i: 0.75, freshness_di: 30, di_class: "A", contribution: 45 },
      { code: "PCF", label: "Протокол чистоты", value: 55, v_i: 0.75, freshness_di: 30, di_class: "A", contribution: 41.3 },
      { code: "FRF", label: "Поглощение фрагментов", value: 55, v_i: 0.75, freshness_di: 30, di_class: "C", contribution: 41.3 },
      { code: "CCF", label: "Контроль концентрации", value: 55, v_i: 0.75, freshness_di: 30, di_class: "A", contribution: 41.3 },
      { code: "RF", label: "Поглощающая фракция", value: 55, v_i: 0.75, freshness_di: 30, di_class: "B", contribution: 41.3 },
      { code: "QEF", label: "Качество энзимов", value: 52, v_i: 0.75, freshness_di: 30, di_class: "A", contribution: 39 },
      { code: "SCIF", label: "Стабильность цепочек", value: 52, v_i: 0.75, freshness_di: 30, di_class: "B", contribution: 39 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 37.3, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0036seedmock", computed_at: "2026-05-27T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.bio-connect.nl" },
  },

  {
    id: "p-037",
    display_name: "Vetter Pharma-Fertigung GmbH & Co. KG",
    role_code: "FILL_FINISH",
    status: "ACTIVE",
    jurisdiction: "Германия (DE)",
    domain: "vetter-pharma.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 71.1,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 100,
    tests_count: 12,
    updated_days_ago: 30,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0037seedmock",
    factors: [
      { code: "QEF", label: "Качество энзимов", value: 92, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 82.8 },
      { code: "PCF", label: "Протокол чистоты", value: 90, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 81 },
      { code: "TRF", label: "Тепловая резистентность", value: 90, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 81 },
      { code: "RF", label: "Поглощающая фракция", value: 90, v_i: 0.9, freshness_di: 30, di_class: "B", contribution: 81 },
      { code: "CCF", label: "Контроль концентрации", value: 88, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 79.2 },
      { code: "SCIF", label: "Стабильность цепочек", value: 82, v_i: 0.9, freshness_di: 30, di_class: "B", contribution: 73.8 },
      { code: "FRF", label: "Поглощение фрагментов", value: 82, v_i: 0.9, freshness_di: 30, di_class: "C", contribution: 73.8 },
      { code: "CVF_B", label: "Валидация компонентов B", value: 78, v_i: 0.9, freshness_di: 30, di_class: "D", contribution: 70.2 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 71.1, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0037seedmock", computed_at: "2026-05-27T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.vetter-pharma.com", email: "info@vetter-pharma.com" },
  },

  {
    id: "p-038",
    display_name: "Corden Pharma GmbH",
    role_code: "FILL_FINISH",
    status: "ACTIVE",
    jurisdiction: "Германия (DE)",
    domain: "cordenpharma.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 73.3,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 100,
    tests_count: 10,
    updated_days_ago: 7,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0038seedmock",
    factors: [
      { code: "RF", label: "Поглощающая фракция", value: 90, v_i: 0.9, freshness_di: 7, di_class: "B", contribution: 81 },
      { code: "QEF", label: "Качество энзимов", value: 88, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 79.2 },
      { code: "CCF", label: "Контроль концентрации", value: 88, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 79.2 },
      { code: "PCF", label: "Протокол чистоты", value: 86, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 77.4 },
      { code: "TRF", label: "Тепловая резистентность", value: 85, v_i: 0.9, freshness_di: 7, di_class: "A", contribution: 76.5 },
      { code: "SCIF", label: "Стабильность цепочек", value: 80, v_i: 0.9, freshness_di: 7, di_class: "B", contribution: 72 },
      { code: "FRF", label: "Поглощение фрагментов", value: 78, v_i: 0.9, freshness_di: 7, di_class: "C", contribution: 70.2 },
      { code: "CVF_B", label: "Валидация компонентов B", value: 72, v_i: 0.9, freshness_di: 7, di_class: "D", contribution: 64.8 },
      { code: "CVF", label: "Валидация компонентов", value: 62, v_i: 0.9, freshness_di: 7, di_class: "D", contribution: 55.8 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 73.3, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0038seedmock", computed_at: "2026-06-19T05:59:11.067Z" },
    ],
    contacts: { website: "https://cordenpharma.com/what-you-need/drug-products/sterile-dosage-forms-aseptic-fill-and-finish/" },
  },

  {
    id: "p-039",
    display_name: "Siegfried Holding AG",
    role_code: "FILL_FINISH",
    status: "ACTIVE",
    jurisdiction: "Швейцария (CH)",
    domain: "siegfried.ch",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 68,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 100,
    tests_count: 15,
    updated_days_ago: 30,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0039seedmock",
    factors: [
      { code: "QEF", label: "Качество энзимов", value: 88, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 79.2 },
      { code: "TRF", label: "Тепловая резистентность", value: 88, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 79.2 },
      { code: "RF", label: "Поглощающая фракция", value: 88, v_i: 0.9, freshness_di: 30, di_class: "B", contribution: 79.2 },
      { code: "CCF", label: "Контроль концентрации", value: 86, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 77.4 },
      { code: "PCF", label: "Протокол чистоты", value: 85, v_i: 0.9, freshness_di: 30, di_class: "A", contribution: 76.5 },
      { code: "FRF", label: "Поглощение фрагментов", value: 82, v_i: 0.9, freshness_di: 30, di_class: "C", contribution: 73.8 },
      { code: "SCIF", label: "Стабильность цепочек", value: 80, v_i: 0.9, freshness_di: 30, di_class: "B", contribution: 72 },
      { code: "CVF_B", label: "Валидация компонентов B", value: 75, v_i: 0.9, freshness_di: 30, di_class: "D", contribution: 67.5 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 68, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0039seedmock", computed_at: "2026-05-27T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.siegfried.ch/offering/drug-products/" },
  },

  {
    id: "p-040",
    display_name: "Recipharm AB",
    role_code: "FILL_FINISH",
    status: "ACTIVE",
    jurisdiction: "Швеция (SE)",
    domain: "recipharm.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 68.7,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 100,
    tests_count: 10,
    updated_days_ago: 14,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0040seedmock",
    factors: [
      { code: "QEF", label: "Качество энзимов", value: 85, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 76.5 },
      { code: "PCF", label: "Протокол чистоты", value: 83, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 74.7 },
      { code: "TRF", label: "Тепловая резистентность", value: 82, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 73.8 },
      { code: "CCF", label: "Контроль концентрации", value: 82, v_i: 0.9, freshness_di: 14, di_class: "A", contribution: 73.8 },
      { code: "RF", label: "Поглощающая фракция", value: 82, v_i: 0.9, freshness_di: 14, di_class: "B", contribution: 73.8 },
      { code: "FRF", label: "Поглощение фрагментов", value: 80, v_i: 0.9, freshness_di: 14, di_class: "C", contribution: 72 },
      { code: "SCIF", label: "Стабильность цепочек", value: 78, v_i: 0.9, freshness_di: 14, di_class: "B", contribution: 70.2 },
      { code: "CVF_B", label: "Валидация компонентов B", value: 65, v_i: 0.9, freshness_di: 14, di_class: "D", contribution: 58.5 },
      { code: "CVF", label: "Валидация компонентов", value: 60, v_i: 0.9, freshness_di: 14, di_class: "D", contribution: 54 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 68.7, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0040seedmock", computed_at: "2026-06-12T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.recipharm.com/drug-product/dosage-forms/sterile-fill-finish" },
  },

  {
    id: "p-041",
    display_name: "Lonza Ltd",
    role_code: "FILL_FINISH",
    status: "ACTIVE",
    jurisdiction: "Швейцария (CH)",
    domain: "lonza.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 65.1,
    tier: "Gold",
    dominant_factor: null,
    is_balanced: true,
    trust_ceiling: 100,
    tests_count: 20,
    updated_days_ago: 60,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0041seedmock",
    factors: [
      { code: "TRF", label: "Тепловая резистентность", value: 95, v_i: 0.9, freshness_di: 60, di_class: "A", contribution: 85.5 },
      { code: "QEF", label: "Качество энзимов", value: 92, v_i: 0.9, freshness_di: 60, di_class: "A", contribution: 82.8 },
      { code: "RF", label: "Поглощающая фракция", value: 92, v_i: 0.9, freshness_di: 60, di_class: "B", contribution: 82.8 },
      { code: "CCF", label: "Контроль концентрации", value: 90, v_i: 0.9, freshness_di: 60, di_class: "A", contribution: 81 },
      { code: "PCF", label: "Протокол чистоты", value: 88, v_i: 0.9, freshness_di: 60, di_class: "A", contribution: 79.2 },
      { code: "SCIF", label: "Стабильность цепочек", value: 85, v_i: 0.9, freshness_di: 60, di_class: "B", contribution: 76.5 },
      { code: "FRF", label: "Поглощение фрагментов", value: 85, v_i: 0.9, freshness_di: 60, di_class: "C", contribution: 76.5 },
      { code: "CVF_B", label: "Валидация компонентов B", value: 85, v_i: 0.9, freshness_di: 60, di_class: "D", contribution: 76.5 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 65.1, dominant_factor: null, algo_version: 'v2.6.0', anchor_hash: "0x0041seedmock", computed_at: "2026-04-27T05:59:11.067Z" },
    ],
    contacts: { website: "https://www.lonza.com/about-us/our-locations/visp-switzerland" },
  },

  {
    id: "p-042",
    display_name: "Adragos Pharma GmbH",
    role_code: "FILL_FINISH",
    status: "ACTIVE",
    jurisdiction: "Германия (DE)",
    domain: "adragos-pharma.com",
    isAnchorRole: true,
    verified_legal: true,
    kyb_level: "L3",
    score: 49.2,
    tier: "Silver",
    dominant_factor: 'QEF',
    is_balanced: false,
    trust_ceiling: 95,
    tests_count: 8,
    updated_days_ago: 83,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0042seedmock",
    factors: [
      { code: "RF", label: "Поглощающая фракция", value: 85, v_i: 0.9, freshness_di: 83, di_class: "B", contribution: 76.5 },
      { code: "QEF", label: "Качество энзимов", value: 82, v_i: 0.9, freshness_di: 83, di_class: "A", contribution: 73.8 },
      { code: "PCF", label: "Протокол чистоты", value: 80, v_i: 0.9, freshness_di: 83, di_class: "A", contribution: 72 },
      { code: "CCF", label: "Контроль концентрации", value: 80, v_i: 0.9, freshness_di: 83, di_class: "A", contribution: 72 },
      { code: "SCIF", label: "Стабильность цепочек", value: 78, v_i: 0.9, freshness_di: 83, di_class: "B", contribution: 70.2 },
      { code: "FRF", label: "Поглощение фрагментов", value: 78, v_i: 0.9, freshness_di: 83, di_class: "C", contribution: 70.2 },
      { code: "TRF", label: "Тепловая резистентность", value: 72, v_i: 0.9, freshness_di: 83, di_class: "A", contribution: 64.8 },
      { code: "CVF", label: "Валидация компонентов", value: 58, v_i: 0.9, freshness_di: 83, di_class: "D", contribution: 52.2 },
    ],
    flags: [],
    score_events: [
      { id: 'e-1', score: 49.2, dominant_factor: 'QEF', algo_version: 'v2.6.0', anchor_hash: "0x0042seedmock", computed_at: "2026-04-04T05:59:11.067Z" },
    ],
    contacts: { website: "https://adragos-pharma.com/sterile-injectable-cdmo-fill-finish-europe/" },
  },

  {
    id: "p-043",
    display_name: "FAMAR S.A.",
    role_code: "FILL_FINISH",
    status: "PROVISIONAL",
    jurisdiction: "GR",
    domain: "famar-group.com",
    isAnchorRole: true,
    verified_legal: false,
    kyb_level: "L1",
    score: 23.7,
    tier: "Bronze",
    dominant_factor: 'QEF',
    is_balanced: false,
    trust_ceiling: 75,
    tests_count: 5,
    updated_days_ago: 294,
    algo_version: 'v2.6.0',
    latest_anchor_hash: "0x0043seedmock",
    factors: [
      { code: "QEF", label: "Качество энзимов", value: 80, v_i: 0.75, freshness_di: 294, di_class: "A", contribution: 60 },
      { code: "PCF", label: "Протокол чистоты", value: 75, v_i: 0.75, freshness_di: 294, di_class: "A", contribution: 56.3 },
      { code: "TRF", label: "Тепловая резистентность", value: 72, v_i: 0.75, freshness_di: 294, di_class: "A", contribution: 54 },
      { code: "FRF", label: "Поглощение фрагментов", value: 72, v_i: 0.75, freshness_di: 294, di_class: "C", contribution: 54 },
      { code: "SCIF", label: "Стабильность цепочек", value: 68, v_i: 0.75, freshness_di: 294, di_class: "B", contribution: 51 },
      { code: "CCF", label: "Контроль концентрации", value: 68, v_i: 0.75, freshness_di: 294, di_class: "A", contribution: 51 },
      { code: "RF", label: "Поглощающая фракция", value: 68, v_i: 0.75, freshness_di: 294, di_class: "B", contribution: 51 },
    ],
    flags: [
      { id: "f-1", type: 'LEGAL_UNVERIFIED', severity: 'INFO', status: 'OPEN', message: 'Юридическое лицо/юрисдикция не верифицированы публично — требуется KYB', raised_at: '2026-06-01T00:00:00Z' },
    ],
    score_events: [
      { id: 'e-1', score: 23.7, dominant_factor: 'QEF', algo_version: 'v2.6.0', anchor_hash: "0x0043seedmock", computed_at: "2025-09-05T05:59:11.067Z" },
    ],
    provisional_reason: "Юрлицо: греческая компания FAMAR S.A. Регистрационный номер GEMI (Generaliko Emporiko Mitroo) не найден в публичном доступе при данном исследовании. Domain исправлен famar.com → famar-group.com. jurisdiction исправлен FR → GR (Famar — греческая компания; HQ Afina/Aainy). Homburg DE площадка управляется Famar Healthcare Germany GmbH (новое DE юрлицо; Handelsregister не верифицирован). GMP статус Homburg (BfArM/EudraGMDP) после перехода от MiP Pharma (закрытие 04.09.2025) требует верификации. ШАГ: поиск в GEMI (gemi.gov.gr) + Handelsregister для Famar Healthcare Germany GmbH.",
    contacts: { website: "https://www.famar-group.com" },
  },
]
